"""Run OSDR-only TabPFN3 flight-vs-ground-control classifiers per tissue."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

from nasa_mouse_glare.io import require_import

from .data import (
    inventory_tables,
    load_dataset,
    log1p_cpm,
    planned_datasets,
)
from .evaluation import metric_dict, run_cv
from .models import backend_status, detect_device, local_model_cache_status
from .paths import DEFAULT_METADATA, DEFAULT_OSDR_API_DIR, DEFAULT_OUTPUT_ROOT, MUSCLE_GROUPS, TARGET_TISSUES
from .plotting import write_plots


def write_inventory(output_root: Path, metadata: Path, tissues: tuple[str, ...]) -> dict[str, str]:
    summary_dir = output_root / "summary"
    summary_dir.mkdir(parents=True, exist_ok=True)
    tables = inventory_tables(metadata, tissues=tissues)
    paths = {
        "tissue_inventory": summary_dir / "osdr_tissue_inventory.tsv",
        "accession_inventory": summary_dir / "osdr_tissue_accession_inventory.tsv",
        "design_inventory": summary_dir / "osdr_tissue_design_inventory.tsv",
        "muscle_split_inventory": summary_dir / "osdr_muscle_split_inventory.tsv",
        "muscle_design_inventory": summary_dir / "osdr_muscle_design_inventory.tsv",
        "sample_inventory": summary_dir / "osdr_sample_inventory.tsv",
    }
    tables["tissue"].to_csv(paths["tissue_inventory"], sep="\t", index=False)
    tables["accession"].to_csv(paths["accession_inventory"], sep="\t", index=False)
    tables["design"].to_csv(paths["design_inventory"], sep="\t", index=False)
    tables["muscle_split"].to_csv(paths["muscle_split_inventory"], sep="\t", index=False)
    tables["muscle_design"].to_csv(
        paths["muscle_design_inventory"], sep="\t", index=False
    )
    tables["sample"].to_csv(paths["sample_inventory"], sep="\t", index=False)
    return {key: str(value) for key, value in paths.items()}


def write_output_readme(output_root: Path, *, backend: str) -> Path:
    path = output_root / "README.md"
    lines = [
        "# TabPFN3 OSDR Outputs",
        "",
        "Generated by src/nasa_mouse_tabpfn3 from NASA OSDR API-derived",
        "metadata and count CSVs. The older raw integrated OSDR H5 files are",
        "not used by this pipeline.",
        "",
        f"Backend requested: {backend}.",
        "",
        "Summary tables are under summary/. Per-dataset folders contain",
        "sample metadata, fold-level predictions/metrics, feature importance,",
        "and plots when model fitting completes.",
        "The aggregate metrics table summarizes each held-out prediction set",
        "by dataset, feature mode, and CV scheme.",
        "The summary inventory includes tissue, accession, material type, sex,",
        "platform, assay, source, and per-sample covariates from the OSDR API.",
        "",
        "If summary/tabpfn3_backend_status.json reports a TabPFN license",
        "error, accept the Prior Labs license, set TABPFN_TOKEN, and rerun.",
        "",
    ]
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def append_manifest(output_root: Path, rows: list[dict]) -> Path:
    pd = require_import("pandas", "pip install -r requirements-nasa-mouse-glare.txt")
    path = output_root / "summary" / "tabpfn3_run_manifest.tsv"
    path.parent.mkdir(parents=True, exist_ok=True)
    frame = pd.DataFrame(rows)
    if path.exists():
        existing = pd.read_csv(path, sep="\t", keep_default_na=False)
        frame = pd.concat([existing, frame], ignore_index=True)
    frame.to_csv(path, sep="\t", index=False)
    return path


def write_summary_tables(
    output_root: Path,
    metrics,
    predictions,
    importance,
    aggregate_metrics,
) -> dict[str, str]:
    summary_dir = output_root / "summary"
    summary_dir.mkdir(parents=True, exist_ok=True)
    paths = {}
    if metrics is not None and not metrics.empty:
        path = summary_dir / "tabpfn3_metrics.tsv"
        metrics.to_csv(path, sep="\t", index=False)
        paths["metrics"] = str(path)
    if predictions is not None and not predictions.empty:
        path = summary_dir / "tabpfn3_predictions.tsv"
        predictions.to_csv(path, sep="\t", index=False)
        paths["predictions"] = str(path)
    if aggregate_metrics is not None and not aggregate_metrics.empty:
        path = summary_dir / "tabpfn3_aggregate_metrics.tsv"
        aggregate_metrics.to_csv(path, sep="\t", index=False)
        paths["aggregate_metrics"] = str(path)
    if importance is not None and not importance.empty:
        path = summary_dir / "tabpfn3_feature_importance.tsv"
        importance.to_csv(path, sep="\t", index=False)
        paths["feature_importance"] = str(path)
    return paths


def aggregate_importance(importance):
    pd = require_import("pandas", "pip install -r requirements-nasa-mouse-glare.txt")
    if importance is None or importance.empty:
        return pd.DataFrame()
    return (
        importance.groupby(
            ["dataset_id", "tissue", "split_group", "feature_mode", "cv_scheme", "gene_id"],
            as_index=False,
        )["mean_decrease_balanced_accuracy"]
        .agg(["mean", "std", "count"])
        .reset_index()
        .rename(
            columns={
                "mean": "mean_decrease_balanced_accuracy",
                "std": "std_decrease_balanced_accuracy",
                "count": "n_fold_gene_tests",
            }
        )
        .sort_values(
            ["dataset_id", "feature_mode", "cv_scheme", "mean_decrease_balanced_accuracy"],
            ascending=[True, True, True, False],
        )
    )


def aggregate_predictions(metrics, predictions):
    pd = require_import("pandas", "pip install -r requirements-nasa-mouse-glare.txt")
    if predictions is None or predictions.empty:
        return pd.DataFrame()

    metric_keys = ["dataset_id", "feature_mode", "cv_scheme"]
    metadata = pd.DataFrame()
    if metrics is not None and not metrics.empty:
        metadata = metrics[
            ["dataset_id", "tissue", "split_group", "feature_mode", "cv_scheme"]
        ].drop_duplicates(metric_keys)

    rows = []
    for keys, group in predictions.groupby(metric_keys, sort=True):
        dataset_id, feature_mode, cv_scheme = keys
        y_true = group["y_true"].astype("int64").to_numpy()
        y_prob = group["p_flight"].astype("float64").to_numpy()
        row = {
            "dataset_id": dataset_id,
            "feature_mode": feature_mode,
            "cv_scheme": cv_scheme,
            **metric_dict(y_true, y_prob),
        }
        if not metadata.empty:
            match = metadata[
                (metadata["dataset_id"] == dataset_id)
                & (metadata["feature_mode"] == feature_mode)
                & (metadata["cv_scheme"] == cv_scheme)
            ]
            if not match.empty:
                row["tissue"] = match.iloc[0]["tissue"]
                row["split_group"] = match.iloc[0]["split_group"]
        rows.append(row)

    frame = pd.DataFrame(rows)
    front = [
        "dataset_id",
        "tissue",
        "split_group",
        "feature_mode",
        "cv_scheme",
        "n_test",
        "n_flight",
        "n_ground_control",
    ]
    ordered = [column for column in front if column in frame.columns]
    ordered.extend([column for column in frame.columns if column not in ordered])
    return frame[ordered].sort_values(["dataset_id", "feature_mode", "cv_scheme"])


def run(args) -> int:
    pd = require_import("pandas", "pip install -r requirements-nasa-mouse-glare.txt")
    output_root = Path(args.output_root)
    output_root.mkdir(parents=True, exist_ok=True)
    write_output_readme(output_root, backend=args.backend)
    summary_dir = output_root / "summary"
    summary_dir.mkdir(parents=True, exist_ok=True)

    tissues = tuple(args.tissues)
    inventory_paths = write_inventory(output_root, Path(args.metadata), tissues)
    plan = planned_datasets(
        tissues,
        include_muscle_splits=args.include_muscle_splits,
        muscle_groups=tuple(args.muscle_groups),
    )
    plan_rows = [
        {
            "dataset_id": tissue if not group else f"{tissue}__{group}",
            "tissue": tissue,
            "split_group": group,
        }
        for tissue, group in plan
    ]
    pd.DataFrame(plan_rows).to_csv(
        summary_dir / "tabpfn3_planned_datasets.tsv", sep="\t", index=False
    )

    selected_device = detect_device(args.device)
    status = backend_status(
        backend=args.backend,
        device=selected_device,
        n_estimators=1,
        random_state=args.random_state,
    )
    status_payload = {
        "backend": args.backend,
        "available": status.available,
        "device": status.device,
        "model_version": status.model_version,
        "message": status.message,
        "model_cache": local_model_cache_status(),
        "metadata": str(args.metadata),
        "api_dir": str(args.api_dir),
        "inventory": inventory_paths,
    }
    (summary_dir / "tabpfn3_backend_status.json").write_text(
        json.dumps(status_payload, indent=2) + "\n", encoding="utf-8"
    )
    if args.inventory_only:
        append_manifest(
            output_root,
            [
                {
                    "status": "inventory_only",
                    "backend": args.backend,
                    "device": status.device,
                    "model_version": status.model_version,
                    "message": "wrote OSDR API inventory and planned datasets",
                }
            ],
        )
        return 0
    if not status.available and args.backend == "tabpfn":
        rows = []
        for item in plan_rows:
            for feature_mode in args.feature_modes:
                rows.append(
                    {
                        **item,
                        "feature_mode": feature_mode,
                        "status": "blocked_backend_unavailable",
                        "backend": args.backend,
                        "device": status.device,
                        "model_version": status.model_version,
                        "message": status.message.replace("\n", " "),
                    }
                )
        append_manifest(output_root, rows)
        print(status.message, file=sys.stderr)
        return 2

    all_metrics = []
    all_predictions = []
    all_importance = []
    manifest_rows = []
    for tissue, split_group in plan:
        dataset_label = tissue if not split_group else f"{tissue}__{split_group}"
        dataset_dir = output_root / dataset_label
        dataset_dir.mkdir(parents=True, exist_ok=True)
        try:
            dataset = load_dataset(
                tissue=tissue,
                split_group=split_group,
                metadata_path=args.metadata,
                api_dir=args.api_dir,
                min_per_condition=args.min_per_condition,
                timeout=args.timeout,
                overwrite_counts=args.overwrite_counts,
                gene_prefix=args.gene_prefix,
            )
            expression = log1p_cpm(dataset.counts)
        except Exception as exc:  # noqa: BLE001 - recorded per dataset.
            manifest_rows.append(
                {
                    "dataset_id": dataset_label,
                    "tissue": tissue,
                    "split_group": split_group,
                    "status": "skipped_data_error",
                    "backend": args.backend,
                    "device": status.device,
                    "model_version": status.model_version,
                    "message": f"{type(exc).__name__}: {exc}",
                }
            )
            continue

        dataset.obs.to_csv(dataset_dir / "sample_metadata.tsv", sep="\t", index=False)
        for feature_mode in args.feature_modes:
            try:
                metrics, predictions, importance = run_cv(
                    dataset=dataset,
                    expression=expression,
                    feature_mode=feature_mode,
                    cv_schemes=tuple(args.cv_schemes),
                    backend=args.backend,
                    device=selected_device,
                    n_estimators=args.n_estimators,
                    hvg_top_n=args.hvg_top_n,
                    min_expr_fraction=args.min_expr_fraction,
                    max_features=args.max_features,
                    importance_candidates=args.importance_candidates,
                    permutation_repeats=args.permutation_repeats,
                    random_state=args.random_state,
                )
            except Exception as exc:  # noqa: BLE001 - recorded per run.
                manifest_rows.append(
                    {
                        "dataset_id": dataset.dataset_id,
                        "tissue": dataset.tissue,
                        "split_group": dataset.split_group,
                        "feature_mode": feature_mode,
                        "status": "failed",
                        "backend": args.backend,
                        "device": status.device,
                        "model_version": status.model_version,
                        "message": f"{type(exc).__name__}: {exc}",
                    }
                )
                if not args.continue_on_error:
                    raise
                continue

            feature_dir = dataset_dir / feature_mode
            feature_dir.mkdir(parents=True, exist_ok=True)
            metrics.to_csv(feature_dir / "cv_metrics.tsv", sep="\t", index=False)
            predictions.to_csv(feature_dir / "cv_predictions.tsv", sep="\t", index=False)
            importance.to_csv(feature_dir / "feature_importance.tsv", sep="\t", index=False)
            write_plots(predictions, importance, feature_dir / "plots", label=f"{dataset.dataset_id}_{feature_mode}")
            all_metrics.append(metrics)
            all_predictions.append(predictions)
            all_importance.append(importance)
            manifest_rows.append(
                {
                    "dataset_id": dataset.dataset_id,
                    "tissue": dataset.tissue,
                    "split_group": dataset.split_group,
                    "feature_mode": feature_mode,
                    "status": "completed",
                    "backend": args.backend,
                    "device": status.device,
                    "model_version": status.model_version,
                    "message": (
                        f"samples={dataset.n_samples}; genes={dataset.n_genes}; "
                        f"fold_rows={len(metrics)}"
                    ),
                }
            )

    metrics_frame = pd.concat(all_metrics, ignore_index=True) if all_metrics else pd.DataFrame()
    predictions_frame = (
        pd.concat(all_predictions, ignore_index=True) if all_predictions else pd.DataFrame()
    )
    importance_frame = (
        aggregate_importance(pd.concat(all_importance, ignore_index=True))
        if all_importance
        else pd.DataFrame()
    )
    aggregate_metrics = aggregate_predictions(metrics_frame, predictions_frame)
    write_summary_tables(
        output_root,
        metrics_frame,
        predictions_frame,
        importance_frame,
        aggregate_metrics,
    )
    append_manifest(output_root, manifest_rows)
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--metadata", default=str(DEFAULT_METADATA))
    parser.add_argument("--api-dir", default=str(DEFAULT_OSDR_API_DIR))
    parser.add_argument("--output-root", default=str(DEFAULT_OUTPUT_ROOT))
    parser.add_argument("--tissues", nargs="+", default=list(TARGET_TISSUES))
    parser.add_argument("--include-muscle-splits", action="store_true", default=True)
    parser.add_argument("--no-muscle-splits", dest="include_muscle_splits", action="store_false")
    parser.add_argument("--muscle-groups", nargs="+", default=list(MUSCLE_GROUPS))
    parser.add_argument("--feature-modes", nargs="+", default=["all_expressed", "hvg"])
    parser.add_argument(
        "--cv-schemes",
        nargs="+",
        default=["random", "grouped", "loo_accession"],
        choices=["random", "grouped", "loo_accession"],
    )
    parser.add_argument("--backend", default="tabpfn", choices=["tabpfn", "sklearn_logreg"])
    parser.add_argument("--device", default="auto")
    parser.add_argument("--n-estimators", type=int, default=8)
    parser.add_argument("--hvg-top-n", type=int, default=2000)
    parser.add_argument("--min-expr-fraction", type=float, default=0.05)
    parser.add_argument("--max-features", type=int, default=0)
    parser.add_argument("--importance-candidates", type=int, default=100)
    parser.add_argument("--permutation-repeats", type=int, default=3)
    parser.add_argument("--min-per-condition", type=int, default=3)
    parser.add_argument("--timeout", type=int, default=120)
    parser.add_argument("--overwrite-counts", action="store_true")
    parser.add_argument("--gene-prefix", default="ENSMUSG")
    parser.add_argument("--inventory-only", action="store_true")
    parser.add_argument("--continue-on-error", action="store_true", default=True)
    parser.add_argument("--stop-on-error", dest="continue_on_error", action="store_false")
    parser.add_argument("--random-state", type=int, default=0)
    return parser


def main(argv: list[str] | None = None) -> int:
    return run(build_parser().parse_args(argv))


if __name__ == "__main__":
    raise SystemExit(main())
